version: 2
updates:
  - package-ecosystem: "terraform"
    directory: "/aws"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "hashicorp/aws"
        update-types: ["version-update:semver-minor"]

  - package-ecosystem: "terraform"
    directory: "/azure"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "hashicorp/azurerm"
        update-types: ["version-update:semver-minor"]

  - package-ecosystem: "gomod"
    directory: "/test"
    schedule:
      interval: "monthly"
